--insert into currency_exchange
--(id, from_currency, to_currency, conversion_multiple, environment)
--values
--((SELECT COALESCE(MAX(id) + 1, 1) from currency_exchange), 'USD', 'NGN', 65, '');
--
--insert into currency_exchange
--(id, from_currency, to_currency, conversion_multiple, environment)
--values
--((SELECT COALESCE(MAX(id) + 1, 1) from currency_exchange), 'EUR', 'NGN', 55, '');
--
--insert into currency_exchange
--(id, from_currency, to_currency, conversion_multiple, environment)
--values
--((SELECT COALESCE(MAX(id) + 1, 1) from currency_exchange), 'AUD', 'NGN', 45, '');